Repository juicyj201/ADP3-Assignment1, pull requests merged in 2022-10, with the labels that each got.

#67 Added one dependency, and fixed meal and order controllers and services.
  pom.xml
  src/main/java/za/ac/cput/Controller/MealController.java
  src/main/java/za/ac/cput/Controller/OrderController.java
  src/main/java/za/ac/cput/Domain/Entity/Meal.java
  src/main/java/za/ac/cput/Domain/Entity/Order.java
  src/main/java/za/ac/cput/Factory/MealFactory.java
  src/main/java/za/ac/cput/Factory/OrderFactory.java
  src/main/java/za/ac/cput/Repository/MealRepository.java
  src/main/java/za/ac/cput/Repository/OrderRepository.java
  src/main/java/za/ac/cput/Service/Impl/MealServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/OrderServiceImpl.java
Labels: bug

#70 Adding major updates to controllers and ui design
  .idea/compiler.xml
  src/main/java/za/ac/cput/Controller/AdminController.java
  src/main/java/za/ac/cput/Controller/EmployeeController.java
  src/main/java/za/ac/cput/Controller/IndexController.java
  src/main/java/za/ac/cput/Controller/LoginController.java
  src/main/java/za/ac/cput/Controller/MainController.java
  src/main/java/za/ac/cput/Domain/Entity/Admin.java
  src/main/java/za/ac/cput/Domain/Entity/Employee.java
  src/main/java/za/ac/cput/Main.java
  src/main/java/za/ac/cput/Repository/AdminRepository.java
  src/main/java/za/ac/cput/Security/WebSecurityConfig.java
  src/main/java/za/ac/cput/Service/Impl/AdminServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/EmployeeServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/Error.html
  src/main/resources/templates/Login.html
  src/main/resources/templates/Main.html
  src/main/resources/templates/index.html
  src/test/java/za/ac/cput/Domain/Entity/MealTest.java
  src/test/java/za/ac/cput/Domain/Entity/OrderTest.java
  src/test/java/za/ac/cput/Factory/MealFactoryTest.java
  src/test/java/za/ac/cput/Factory/OrderFactoryTest.java
Labels: enhancement

#72 Web components.
  src/main/resources/static/css/index-not-logged-in.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/navbar.css
  src/main/resources/templates/Login.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  target/classes/za/ac/cput/Security/ApplicationUserPermission.class
  target/classes/za/ac/cput/Security/ApplicationUserRole.class
Labels: enhancement

#74 Updating student and student account controller
  src/main/java/za/ac/cput/Controller/StudentAccountController.java
  src/main/java/za/ac/cput/Controller/StudentController.java
Labels: enhancement

#75 Adding documentation
  README.md
Labels: documentation

#76 Added long type parameters for read methods in services
  src/main/java/za/ac/cput/Controller/LoginController.java
  src/main/java/za/ac/cput/Controller/MainController.java
  src/main/java/za/ac/cput/Domain/Entity/Admin.java
  src/main/java/za/ac/cput/Factory/AdminFactory.java
  src/main/java/za/ac/cput/Repository/AdminRepository.java
  src/main/java/za/ac/cput/Service/IService.java
  src/main/java/za/ac/cput/Service/Impl/AdminService.java
  src/main/java/za/ac/cput/Service/Impl/AdminServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/EmployeeServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/MealServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/OrderServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/PaymentServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/RestaurantServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/StudentAccountServiceImpl.java
  src/main/java/za/ac/cput/Service/Impl/StudentServiceImpl.java
  src/main/resources/templates/LoginAdmin.html
  src/main/resources/templates/LoginEmployee.html
  src/main/resources/templates/index.html
  src/test/java/za/ac/cput/Service/Impl/AdminServiceImplTest.java
Labels: enhancement

#77 Adding bug fixes
  src/main/java/za/ac/cput/Controller/AdminController.java
  src/main/java/za/ac/cput/Controller/LoginController.java
  src/main/java/za/ac/cput/Controller/MainController.java
  src/main/java/za/ac/cput/Controller/PaymentController.java
  src/main/java/za/ac/cput/Controller/RestaurantController.java
  src/main/java/za/ac/cput/Domain/Entity/Admin.java
  src/main/java/za/ac/cput/Domain/Entity/Payment.java
  src/main/java/za/ac/cput/Factory/AdminFactory.java
  src/main/java/za/ac/cput/Factory/PaymentFactory.java
  src/main/java/za/ac/cput/Service/Impl/RestaurantServiceImpl.java
  src/main/resources/templates/Login.html
  src/main/resources/templates/Main.html
  src/main/resources/templates/index.html
  src/test/java/za/ac/cput/Controller/AdminControllerTest.java
  src/test/java/za/ac/cput/Controller/PaymentControllerTest.java
  src/test/java/za/ac/cput/Domain/Entity/AdminTest.java
  src/test/java/za/ac/cput/Domain/Entity/PaymentTest.java
  src/test/java/za/ac/cput/Factory/AdminFactoryTest.java
  src/test/java/za/ac/cput/Factory/PaymentFactoryTest.java
  src/test/java/za/ac/cput/Service/Impl/PaymentServiceImplTest.java
  target/classes/static/css/navbar.css
  target/classes/templates/Main.html
  target/classes/templates/index.html
  target/classes/za/ac/cput/Controller/AdminController.class
  target/classes/za/ac/cput/Controller/LoginController.class
  target/classes/za/ac/cput/Controller/MainController.class
  target/classes/za/ac/cput/Controller/PaymentController.class
  target/classes/za/ac/cput/Controller/RestaurantController.class
  target/classes/za/ac/cput/Controller/StudentAccountController.class
  target/classes/za/ac/cput/Controller/StudentController.class
  target/classes/za/ac/cput/Domain/Entity/Admin.class
  target/classes/za/ac/cput/Domain/Entity/Payment.class
  target/classes/za/ac/cput/Repository/AdminRepository.class
  target/classes/za/ac/cput/Service/IService.class
  target/classes/za/ac/cput/Service/Impl/AdminService.class
  target/classes/za/ac/cput/Service/Impl/AdminServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/EmployeeServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/MealServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/OrderServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/PaymentServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/RestaurantServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/StudentAccountServiceImpl.class
  target/classes/za/ac/cput/Service/Impl/StudentServiceImpl.class
  target/test-classes/za/ac/cput/Controller/AdminControllerTest.class
  target/test-classes/za/ac/cput/Controller/PaymentControllerTest.class
  target/test-classes/za/ac/cput/Service/Impl/AdminServiceImplTest.class
  target/test-classes/za/ac/cput/Service/Impl/PaymentServiceImplTest.class
Labels: bug

#89 Updating web security bug and controllers tests
  resources/restaurantDB.mv.db
  resources/restaurantDB.trace.db
  src/main/java/za/ac/cput/Security/WebSecurityConfig.java
  src/test/java/za/ac/cput/Controller/AdminControllerTest.java
  src/test/java/za/ac/cput/Controller/MealControllerTest.java
  src/test/java/za/ac/cput/Controller/OrderControllerTest.java
  src/test/java/za/ac/cput/Controller/PaymentControllerTest.java
  src/test/java/za/ac/cput/Controller/StudentAccountControllerTest.java
  src/test/java/za/ac/cput/Controller/StudentControllerTest.java
  target/classes/templates/LoggedInUser.html
  target/classes/templates/Main.html
  target/classes/za/ac/cput/Controller/AdminController.class
  target/classes/za/ac/cput/Controller/PaymentController.class
  target/classes/za/ac/cput/Security/WebSecurityConfig.class
  target/test-classes/za/ac/cput/Controller/AdminControllerTest.class
  target/test-classes/za/ac/cput/Controller/MealControllerTest.class
  target/test-classes/za/ac/cput/Controller/OrderControllerTest.class
  target/test-classes/za/ac/cput/Controller/PaymentControllerTest.class
  target/test-classes/za/ac/cput/Controller/StudentAccountControllerTest.class
  target/test-classes/za/ac/cput/Controller/StudentControllerTest.class
Labels: enhancement
